import test from 'node:test';import assert from 'node:assert/strict';
import {fixture} from './negative-fixture-08.1.6-fix2-4.mjs';
import {buildNegativeRepairProof,applyNegativeRepairToScenario} from '../src/negativeRequestRepair.js';
import {validateDerivedVersionInput} from '../src/validation/testDesignEvolution.js';
import {validateAppendVersionInput} from '../src/validation/testDesignVersion.js';
import {appendPayload} from './fixtures.mjs';
const missing='get_custom_fields_missing_id',query='get_custom_fields_invalid_query_param';
async function selected(id){const f=fixture();return {...f,source:f.source(id),proof:await buildNegativeRepairProof({sourceVersion:f.sourceVersion,resultSet:f.resultSet,scenario:f.result(id)})};}
for(const id of [missing,query])test('repaired scenario preserves identity, auth, assertions and leaves expectation in review: '+id,async()=>{const f=await selected(id),before=structuredClone(f.source),n=await applyNegativeRepairToScenario(f.source,f.proof,f.sourceVersion);assert.deepEqual(f.source,before);assert.deepEqual(n.spec.target,before.spec.target);assert.deepEqual(n.spec.auth,before.spec.auth);assert.deepEqual(n.spec.assertions,before.spec.assertions);assert.equal(n.automation.readiness,'REVIEW_REQUIRED');assert.equal(n.spec.negativeStrategy.operation,id===missing?'OMIT_PATH_SEGMENT':'QUERY_VALUE_PROBE');});
test('registry adds positional ordinary dependency, never a literal captured ID',async()=>{const f=await selected(query),n=await applyNegativeRepairToScenario(f.source,f.proof,f.sourceVersion);assert.deepEqual(n.spec.request.pathParams,{});assert.equal(n.spec.testData.bindings[0].bindingKey,'PATH_PARAM:id@6:0');assert.equal(n.spec.testData.bindings[0].source,'OBSERVED');assert.ok(!n.spec.testData.bindings.some(b=>b.selector==='screen'));});
test('wrong scope, source hash, binding position, operation or value is refused',async()=>{const f=await selected(query);for(const edit of [x=>x.projectId='prj_other',x=>x.sourceScenarioHash='f'.repeat(64),x=>x.addedBindings[0].bindingKey='PATH_PARAM:id@0:0',x=>x.strategy.selector='password',x=>x.strategy.probeValue='model-arbitrary-value',x=>x.strategy.sourcePath='/other']){const p=structuredClone(f.proof);edit(p);await assert.rejects(applyNegativeRepairToScenario(f.source,p,f.sourceVersion));}});
test('request strategy cannot be inserted through ordinary AI generation append',async()=>{const f=await selected(missing),s=f.sourceVersion.specification;s.scenarios.find(x=>x.scenarioId===missing).spec.negativeStrategy=f.proof.strategy;assert.throws(()=>validateAppendVersionInput(appendPayload({...f.sourceVersion,specification:s,contextFingerprint:'f'.repeat(64),metadata:{provider:'fixture',model:'synthetic',promptVersion:'fixture',repairPromptVersion:'fixture',guardVersion:'fixture'}})),e=>e.code==='NEGATIVE_REQUEST_REPAIR_APPROVAL_REQUIRED');});
test('reviewed derivation requires actor, provenance and no competing change in same scenario',async()=>{const f=await selected(missing),p=f.proof,ls={proposalId:'tep_repair',resultSetId:p.resultSetId,scenarioResultId:p.scenarioResultId,runId:p.runId,testDesignVersionId:p.testDesignVersionId,environmentId:p.environmentId},input={organizationId:p.organizationId,projectId:p.projectId,sourceTestDesignVersionId:p.testDesignVersionId,derivation:{type:'RESULT_EVOLUTION',proposalId:ls.proposalId,sourceResultSetId:ls.resultSetId,sourceScenarioResultId:ls.scenarioResultId,approvedByUserId:'usr_review',approvalReason:'Review explicit missing path segment'},changes:[{type:'NEGATIVE_REQUEST_REPAIR',scenarioId:missing,assertionIndex:0,repairProof:p,learningSource:ls}]};assert.equal(validateDerivedVersionInput(input).changes[0].type,'NEGATIVE_REQUEST_REPAIR');for(const edit of [x=>delete x.derivation.approvedByUserId,x=>x.changes[0].learningSource.resultSetId='rset_other',x=>x.changes.push({type:'STATUS_EXPECTATION',scenarioId:missing,assertionIndex:0,expectedStatusCodes:[200]})]){const bad=structuredClone(input);edit(bad);assert.throws(()=>validateDerivedVersionInput(bad));}});
