import test from 'node:test';
import assert from 'node:assert/strict';
import { applyCurrentMigrations } from './helpers/currentMigrations.mjs';
import { SQLiteD1 } from './helpers/sqliteD1.mjs';
import { appendPayload, sampleSpecification } from './fixtures.mjs';
import { handleRequest } from '../src/index.js';

const headers={'content-type':'application/json','x-qagent-organization-id':'org_test','x-qagent-project-id':'prj_test'};
const env=db=>({TEST_REGISTRY_DB:db,TEST_REGISTRY_MAX_SPEC_BYTES:'262144',TEST_REGISTRY_MAX_REQUEST_BYTES:'393216'});
function sourceSpec(){const spec=sampleSpecification({readiness:'READY'});const a=spec.scenarios[0];a.scenarioId='scenario_a';a.title='Original';a.objective='Original objective';const b=structuredClone(a);b.scenarioId='scenario_b';b.title='Sibling';spec.scenarios=[a,b];spec.summary.scenarioCount=2;spec.summary.readyCount=2;spec.summary.byReadiness={READY:2};return spec;}
async function createBase(db){const base=appendPayload({generationRequestId:'tdg_lifecycle_base',specification:sourceSpec()});const res=await handleRequest(new Request('https://r/v1/test-registry/test-designs/versions',{method:'POST',headers,body:JSON.stringify(base)}),env(db));assert.equal(res.status,201);return (await res.json()).data.testDesign;}
async function latest(db){const res=await handleRequest(new Request('https://r/v1/test-registry/projects/prj_test/endpoints/cep_orders/test-design/latest',{headers}),env(db));return (await res.json()).data.version.specification;}
function request(payload){return new Request('https://r/internal/v1/test-registry/test-designs/scenario-lifecycle',{method:'POST',headers,body:JSON.stringify(payload)});}
function payload(versionId,operation){return {contractVersion:'qagent.scenario-lifecycle-registry.v1',organizationId:'org_test',projectId:'prj_test',endpointId:'cep_orders',sourceTestDesignVersionId:versionId,operation:{approvedByUserId:'usr_1',reason:'test',...operation}};}

test('FIX-3.1 clone creates new scenario without copying learning history and is idempotent',async()=>{const db=new SQLiteD1();applyCurrentMigrations(db);try{const first=await createBase(db);const p=payload(first.versionId,{operationId:'slo_clone_1',action:'CLONE',scenarioId:'scenario_a',newScenarioId:'scenario_clone',title:'Clone'});const r=await handleRequest(request(p),env(db));assert.equal(r.status,201);const data=(await r.json()).data;assert.equal(data.testDesign.version,2);const spec=await latest(db);assert.equal(spec.scenarios.length,3);const clone=spec.scenarios.find(s=>s.scenarioId==='scenario_clone');assert.equal(clone.title,'Clone');assert.equal(clone.scenarioLifecycle.kind,'SCENARIO_CLONE');assert.equal(clone.scenarioLifecycle.sourceScenarioId,'scenario_a');const replay=await handleRequest(request(p),env(db));assert.equal(replay.status,200);assert.equal((await replay.json()).data.testDesign.versionId,data.testDesign.versionId);}finally{db.close();}});

test('FIX-3.1 rename changes metadata only and remove preserves immutable parent',async()=>{const db=new SQLiteD1();applyCurrentMigrations(db);try{const first=await createBase(db);const rr=await handleRequest(request(payload(first.versionId,{operationId:'slo_rename_1',action:'RENAME',scenarioId:'scenario_a',title:'Renamed',objective:'Updated objective'})),env(db));assert.equal(rr.status,201);const renamed=(await rr.json()).data.testDesign;let spec=await latest(db);const a=spec.scenarios.find(s=>s.scenarioId==='scenario_a');assert.equal(a.title,'Renamed');assert.equal(a.objective,'Updated objective');assert.equal(a.spec.target.path,sourceSpec().scenarios[0].spec.target.path);const rem=await handleRequest(request(payload(renamed.versionId,{operationId:'slo_remove_1',action:'REMOVE',scenarioId:'scenario_b'})),env(db));assert.equal(rem.status,201);spec=await latest(db);assert.deepEqual(spec.scenarios.map(s=>s.scenarioId),['scenario_a']);assert.equal(spec.summary.scenarioCount,1);}finally{db.close();}});

test('FIX-3.1 protects observed baselines and refuses removing last scenario',async()=>{const db=new SQLiteD1();applyCurrentMigrations(db);try{const first=await createBase(db);let spec=await latest(db);const baseline=spec.scenarios[0];baseline.generationClass='OBSERVED_BASELINE';// create a second independent root with baseline source
const other=appendPayload({generationRequestId:'tdg_lifecycle_baseline',endpointId:'cep_baseline',specification:{...sourceSpec(),source:{...sourceSpec().source,endpointId:'cep_baseline'},scenarios:[baseline]}});const created=await handleRequest(new Request('https://r/v1/test-registry/test-designs/versions',{method:'POST',headers,body:JSON.stringify(other)}),env(db));assert.equal(created.status,201);const td=(await created.json()).data.testDesign;const bad={...payload(td.versionId,{operationId:'slo_base',action:'CLONE',scenarioId:baseline.scenarioId,newScenarioId:'clone'}),endpointId:'cep_baseline'};const blocked=await handleRequest(request(bad),env(db));assert.equal(blocked.status,409);
// create one-scenario normal root
const single=appendPayload({generationRequestId:'tdg_lifecycle_single',endpointId:'cep_single',specification:{...sourceSpec(),source:{...sourceSpec().source,endpointId:'cep_single'},scenarios:[sourceSpec().scenarios[0]],summary:{...sourceSpec().summary,scenarioCount:1,readyCount:1,byReadiness:{READY:1}}}});const sr=await handleRequest(new Request('https://r/v1/test-registry/test-designs/versions',{method:'POST',headers,body:JSON.stringify(single)}),env(db));const std=(await sr.json()).data.testDesign;const remove={...payload(std.versionId,{operationId:'slo_last',action:'REMOVE',scenarioId:'scenario_a'}),endpointId:'cep_single'};const last=await handleRequest(request(remove),env(db));assert.equal(last.status,409);
}finally{db.close();}});
